spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campusdb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Hyp@060911
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080